### ISSUE TITLE
Issues about NCHW and in_channel

### ISSUE THREAD

**Issue by Neo-YH** [JunweiLiang/Object_Detection_Tracking#14]
![image](https://user-images.githubusercontent.com/62652681/79069963-d085eb00-7d04-11ea-86b8-f6f01ff78f5e.png)
学长，我执行代码时报了default maxpooling only support NHWC的问题，我看网上的解决方案把NCHW全替换成了NHWC。这个报错消失了，但是接下来Assert in_channel is not None出问题了。
![image](https://user-images.githubusercontent.com/62652681/79069972-f01d1380-7d04-11ea-9e40-b59020741b90.png)
我看我把NCHW全部替换之后channel_axis就只能等于3了，in_shape取出来的就是None。不太理解这个过程，我应该怎么修复这个报错啊。万分感谢学长。

**Comment by JunweiLiang** [comment]
第一个错误看起来是你的TF没有装GPU版本，你看一下下面代码的输出是否0:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
改成NHWC的话，很多代码都需要相应改变进行transpose操作，不建议改。

**Comment by Neo-YH** [comment]
感谢学长，确实是GPU的问题，重装了CUDA，cuDNN对应的tensorflow-gpu之后报错就解决了
![image](https://user-images.githubusercontent.com/62652681/79095601-61080e00-7d8d-11ea-91b5-204ae784e68c.png)
