### ISSUE TITLE
About tensorflow-gpu version

### ISSUE THREAD

**Issue by Neo-YH** [JunweiLiang/Object_Detection_Tracking#16]
![image](https://user-images.githubusercontent.com/62652681/79686391-9a9bb600-8272-11ea-8fd3-557ad0b88f8a.png)

学长，我看网上说出现这个问题的时候，用下面这个命令
pip install --ignore-installed --upgrade --ignore-installed tensorflow-gpu
但是这样的话就会装上tensorflow-gpu==2.1.0的版本，跟本机上现有的CUDA9.0版本和cuDNN7.3版本就不匹配了，这个应该怎么办啊

**Comment by Neo-YH** [comment]
![image](https://user-images.githubusercontent.com/62652681/79686460-1990ee80-8273-11ea-8b72-5526397134eb.png)

**Comment by JunweiLiang** [comment]
请使用tensorflow==1.15
