### ISSUE TITLE
Unable to get TRACK ID

### ISSUE THREAD

**Issue by devendraswamy** [JunweiLiang/Object_Detection_Tracking#17]
I am not able to get the  track id for detected objects while I am running the inference  code.

**Comment by JunweiLiang** [comment]
You are gonna need to be more specific than that. What environment did you run on? What commands did you run? What videos? What is the expected output? etc.

**Comment by devendraswamy** [comment]
I am using conda environment , I had run the inference commands which you have given in the readme file , I got detection's and the confidence levels  but I did not get the object track ID ( I am expecting  detection along with the track ID)

**Comment by JunweiLiang** [comment]
If you follow the instruction, the tracking results will be in `test_track_out` folder or whatever directory you provide for `--tracking_dir`.
If you want more help, provide the *exact* command you have run, your command line output, and the directory content of `test_track_out`.

**Comment by devendraswamy** [comment]
$python obj_detect_tracking.py --model_path obj_v3_model --version 3 --video_dir v1-val_testvideos --video_lst_file v1-val_testvideos.lst --frame_gap 1 --get_tracking --tracking_dir test_track_out --out_dir test_json_out --visualize --vis_path test_vis_out

$ ls $PWD/v1-val_testvideos/* > v1-val_testvideos.abs.lst

$ python get_frames_resize.py v1-val_testvideos.abs.lst v1-val_testvideos_frames/ --use_2level

$ python tracks_to_json.py test_track_out/ v1-val_testvideos.abs.lst test_track_out_json

$ python vis_json.py v1-val_testvideos.abs.lst v1-val_testvideos_frames/ test_track_out_json/ test_track_out_vis

$ ffmpeg -framerate 30 -i test_track_out_vis/VIRAT_S_000205_05_001092_001124/VIRAT_S_000205_05_001092_001124_F_%08d.jpg vis_video_2.mp4

I run above commands and i am getting result video but in video track id was not there (like #1 ,#2, #3), help me i need to get the video with track ID on every object detection box on video(which you provide in your repo , like that)

**Comment by devendraswamy** [comment]
I am almost completed but I am waiting for getting a track id in video , so please tell me how can i get track id on video objects, thanking you

**Comment by devendraswamy** [comment]
who can help me(appreciated) , i am still facing that above problem  , Thanking you !

**Comment by wangguan1024** [comment]
vis_json.py, 261th line, if "trackId" not in one:, remove "not".

**Comment by JunweiLiang** [comment]
Thanks @wangguan1024 for pointing this out. I have fixed this bug. @devendraswamy it should work now.

**Comment by wangguan1024** [comment]
It's an honor to make this project better. What's more, I have some questions and&nbsp;I look forward to getting help from you.
If I add "get_tracking" in args, these code will be run. Then the tracking classes only include person and vehicle. How could I increase class the tracker can track? I am a Chinese Student, my English is a little poor, could you help me in Chinese? 谢谢你！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JunweiLiang/Object_Detection_Tracking"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 晚上9:59
收件人:&nbsp;"JunweiLiang/Object_Detection_Tracking"<Object_Detection_Tracking@noreply.github.com&gt;;
抄送:&nbsp;"1104463324"<1104463324@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JunweiLiang/Object_Detection_Tracking] Unable to get TRACK ID (#17)





 
Thanks @wangguan1024 for pointing this out. I have fixed this bug. @devendraswamy it should work now.

**Comment by JunweiLiang** [comment]
Depending on the model you use (ActEV model or COCO model), you can add the tracking objects according to [this argument](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/obj_detect_tracking.py#L148). The objects names are comma-separated. To check out what object classes are available, please refer to [class_ids.py](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/class_ids.py#L39). Sure you can write Chinese if you want.

**Comment by wangguan1024** [comment]
很高兴得到您的回复。
请看下图，我想使用预训练的efficientdet作为目标检测模型，按照您的意思，如果我去掉了use_partial_classes参数, tracking_objs这个参数的值就可以设置为coco_id_mapping中90个类别的任意组合吗？

**Comment by JunweiLiang** [comment]
对的，是80个类，参照[这里](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/class_ids.py#L526)

**Comment by wangguan1024** [comment]
好的，谢谢您。我已经调整代码修改成功了，主要是修改了object_detect_tracking.py调用的util.py, tracks_to_json.py这两个文件中的关于targetClass2id的赋值，用coco_obj_class_to_id 替代了 coco_obj_to_actev_obj，然后在命令行调用时指定的追踪类就可以是coco的80个类了。非常感谢远在大洋彼岸的您。祝您身体健康，工作顺利。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "JunweiLiang/Object_Detection_Tracking"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 凌晨3:41
收件人:&nbsp;"JunweiLiang/Object_Detection_Tracking"<Object_Detection_Tracking@noreply.github.com&gt;;
抄送:&nbsp;"1104463324"<1104463324@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JunweiLiang/Object_Detection_Tracking] Unable to get TRACK ID (#17)





 
对的，是80个类，参照这里
