### ISSUE TITLE
efficientdet-d6

### ISSUE THREAD

**Issue by aleksandar** [JunweiLiang/Object_Detection_Tracking#18]
Hi, really nice work!

I tried to run the script with model EfficientDet-d6, but without success. All prediction were bellow 10-15%. The frozen model version doesn't work because tf versions i guess. 

Is there an easy way to solve this?

Thanks,
Aleksandar

**Comment by JunweiLiang** [comment]
Hi, thanks. The current EfficientDet code is based on their March version, which requires March version models. I only have [d0](https://aladdin-eax.inf.cs.cmu.edu/shares/diva_obj_detect_models/models/efficientdet-d0.tar.gz) model saved. I will be implementing their current version soon.

**Comment by JunweiLiang** [comment]
I have updated the repo with the latest EfficientDet. They should work now.
