### ISSUE TITLE
Ask for updating instruction for training and testing 

### ISSUE THREAD

**Issue by houzhijian** [JunweiLiang/Object_Detection_Tracking#2]
Hi, thanks for sharing.

In the model module of the README,md file, you said that  I will add instruction for training and testing if requested.  

I appreciate it very much when you can update that part.

**Comment by JunweiLiang** [comment]
Will add it in a month in my spare time.

**Comment by JunweiLiang** [comment]
Added.

**Comment by houzhijian** [comment]
Hi, when do testing in TRAINING.md file

When I process 
wget https://aladdin-eax.inf.cs.cmu.edu/shares/diva_obj_detect_models/v1-validate_frames.lst

It shows ERROR 404: Not Found.

Yeah. I have checked the website. It seems that you have forgotten to upload this file. Hope you can add it, thank you.

**Comment by JunweiLiang** [comment]
Added. Thanks.
