### ISSUE TITLE
Can you please provide performance related metrics of your model Argus?

### ISSUE THREAD

**Issue by malarsaravanan1991** [JunweiLiang/Object_Detection_Tracking#21]
Hi,
Thanks for the wonderful work. I am trying to compare "Argus" with my work in terms of model performance metrics. Can you please provide the below details regarding your model "Argus":
1. number of trainable parameters
2. GFLOP's(floating point operation)
3. Inference fps and details of the GPU used

Any help is much appreciated. Also can you please point to the code where Pmiss rate is calculated?

**Comment by JunweiLiang** [comment]
The Argus model is out-of-scope for this repository. You can send an email to the first author for that.
