### ISSUE TITLE
Is there a pretrained activity detection model?

### ISSUE THREAD

**Issue by ysl208** [JunweiLiang/Object_Detection_Tracking#23]
Great work! 
I managed to run the inferencing with `obj_detect_tracking.py` but the results don't show the activity but only the object detection & tracking.

I was wondering if you could provide a pretrained activity detection model since I am having trouble downloading the full ActEv dataset and am mainly interested in testing it?

**Comment by JunweiLiang** [comment]
Thanks,
The scope of this repo is for object detection and tracking in videos only. It's not my decision to whether release the activity detection code but I think we would do it next year.
For downloading ActEV, you can get the data from here: https://gitlab.kitware.com/actev/actev-data-repo
And here: https://data.kitware.com/#collection/56f56db28d777f753209ba9f/folder/56f57e748d777f753209bed6
