### ISSUE TITLE
Errors when following instructions for Frame-level Activity Detection Experiments

### ISSUE THREAD

**Issue by ysl208** [JunweiLiang/Object_Detection_Tracking#24]
Hi, sorry I'm still a bit unfamiliar with obejct detection/tracking. I tried to follow your instructions but I got a bit confused and am also getting some error messages. 

I downloaded the pretrained MSCOCO model from Tensorpack and would like to run the testing steps:

```
python main.py nothing v1-validate_frames.lst --mode forward --outbasepath \
actbox_v1_test --rpn_batch_size 256 --frcnn_batch_size 512 --num_class 10 --bupt_exp \
--max_size 1920 --short_edge_size 1080 --rpn_test_post_nms_topk 1000 --gpu 1 --is_fpn \
--im_batch_size 1 --load_from bupt_actboxexp_resnet101_dilation_classagnostic/ \mrcnn101/01/save-best/ --use_dilation --use_frcnn_class_agnostic --log
```
But I get the following error:

```
Exception: Not recognized model type:bupt_actboxexp_resnet101_dilation_classagnostic/mrcnn101/01/save-best/
```

Also, what is the difference between testing and evaluate?
When I run the evaluate command `python eval.py v1-validate_frames.lst v1-validate_012019_actgt_allsingle_npz \
actbox_v1_test --bupt_exp` I get an error message:
```
100%|##################################################################################################| 206268/206268 [00:00<00:00, 321939.66it/s]
0/206268 out file not exists
9 class has no ground truth: ['Person-Vehicle', 'Vehicle-Turning', 'activity_carrying', 'Transport_HeavyCarry', 'Talking', 'Pull', 'Riding', 'specialized_texting_phone', 'specialized_talking_phone']
Traceback (most recent call last):
  File "eval.py", line 250, in <module>
    aps, ars = aggregate_eval(e, maxDet=100)
  File "/home/liangyi/Projects/Object_Detection_Tracking/utils.py", line 281, in aggregate_eval
    for imageid in e_c])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```
Could you clarify?

**Comment by JunweiLiang** [comment]
The first error means you did not download the `bupt_actboxexp_resnet101_dilation_classagnostic` model. This is the activity detection model, not the MSCOCO model. The second error is because you did not have outputs to evaluate. The `main.py` file is used to train/validate/test the models. When testing the models you can save the detection output into files. The `eval.py` takes the output files and computes AP. Please read the [tutorial](https://github.com/JunweiLiang/Object_Detection_Tracking#inferencing) and follow it step-by-step.

**Comment by ysl208** [comment]
Thanks for your fast response.
Where can I download the `bupt_actboxexp_resnet101_dilation_classagnostic` model for activity detection?

**Comment by JunweiLiang** [comment]
The frame-level activity detection model is not provided since the performance is not good. You can easily train one following this [tutorial](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/ACTIVITY_BOX.md).
