### ISSUE TITLE
How to add Bicycle etc. clase?

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Object_Detection_Tracking#25]
This model is tracking "Person" and "Vehicle" class.
How to add Bicycle etc. clase?
Also if I want to add other classes, which code should I change?

**Comment by JunweiLiang** [comment]
See the `--tracking_objs` parameter [here](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/obj_detect_tracking.py#L148). The default is `Person,Vehicle`. You can simply add additional object class names (comma separated) according to the name list [here](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/class_ids.py#L39). You can only do this with VIRAT trained object models (v1-6).
