### ISSUE TITLE
Putting npz file in the test video path

### ISSUE THREAD

**Issue by wangwyForNewTime** [JunweiLiang/Object_Detection_Tracking#26]
When I run object  detection&tracking on the videos ,it returns : Warning,cannot open v1-val-testvideos/COCO-MaskRCNN-R101FPN1x.npz.What should I do?

(ForObjectDetectionTrack) user@ubuntu:~/WWY/Object_Detection_Tracking-master/Object_Detection_Tracking-master$ python obj_detect_tracking.py --model_path obj_v3_model --version 3 --video_dir v1-val_testvi
deos --video_lst_file v1-val_testvideos.lst --frame_gap 1 --get_tracking --tracking_dir test_track_out
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-11
OMP: Info #214: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #156: KMP_AFFINITY: 12 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #285: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "core".
OMP: Info #285: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "core".
OMP: Info #285: KMP_AFFINITY: topology layer "thread" is equivalent to "core".
OMP: Info #191: KMP_AFFINITY: 1 socket x 12 cores/socket x 1 thread/core (12 total cores)
OMP: Info #216: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 3 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to socket 0 core 4 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to socket 0 core 5 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to socket 0 core 8 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to socket 0 core 9 
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to socket 0 core 10 
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to socket 0 core 11 
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to socket 0 core 12 
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to socket 0 core 13 
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25004 thread 0 bound to OS proc set 0
0%| | 0/2 [00:00<?, ?it/s]warning, cannot open v1-val_testvideos/COCO-MaskRCNN-R101FPN1x.npz
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25047 thread 1 bound to OS proc set 1
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25075 thread 3 bound to OS proc set 3
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25074 thread 2 bound to OS proc set 2
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25076 thread 4 bound to OS proc set 4
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25077 thread 5 bound to OS proc set 5
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25079 thread 7 bound to OS proc set 7
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25080 thread 8 bound to OS proc set 8
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25081 thread 9 bound to OS proc set 9
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25082 thread 10 bound to OS proc set 10
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25084 thread 12 bound to OS proc set 0
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25083 thread 11 bound to OS proc set 11
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25078 thread 6 bound to OS proc set 6
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25048 thread 13 bound to OS proc set 1
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25085 thread 14 bound to OS proc set 2
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25086 thread 15 bound to OS proc set 3
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25087 thread 16 bound to OS proc set 4
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25088 thread 17 bound to OS proc set 5
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25089 thread 18 bound to OS proc set 6
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25091 thread 20 bound to OS proc set 8
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25092 thread 21 bound to OS proc set 9
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25090 thread 19 bound to OS proc set 7
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25093 thread 22 bound to OS proc set 10
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25094 thread 23 bound to OS proc set 11
OMP: Info #252: KMP_AFFINITY: pid 25004 tid 25095 thread 24 bound to OS proc set 0
100%|#################################################################| 2/2 [43:34<00:00, 1307.06s/it]

**Comment by JunweiLiang** [comment]
This happens because you put a npz file in your test video path. The code tries to open and do object detection and tracking for everything you put in `v1-val_testvideos.lst`, which includes `COCO-MaskRCNN-R101FPN1x.npz`. It is obviously not a video.
