### ISSUE TITLE
MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by ThomsonW** [JunweiLiang/Object_Detection_Tracking#27]
i downloaded the project, both code and model, and i run the demo coded in obj_detect_tracking.py with the example args .
then an error occurred:

 tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU

and i located the problem at Line782 in nn.py, which defined the function called MaxPooling.

i am not so familiar with tensorflow, so how can i fix this issues?
thanks!

**Comment by JunweiLiang** [comment]
The code only works with Tensorflow-GPU.
