### ISSUE TITLE
imshow

### ISSUE THREAD

**Issue by farecomhalima** [JunweiLiang/Object_Detection_Tracking#29]
Hello I have a problem I can't get the whole image when I do imshow in "Obj_detect_tracking.py" (just before the imwrite in the visualize section): with imwrite I have in the file the image with Bounding box but with imshow I have just the bounding box.

**Comment by JunweiLiang** [comment]
What do you mean with imshow? I don't have cv2.imshow in the code. cv2.imwrite and cv2.imshow both take a numpy image array as input so you should get the same thing.

**Comment by farecomhalima** [comment]
Thanks for replying so fast. Yes there is no cv2.imshow in your code but for my project i need to visualize not to save the output image. Yes, but unfortunately i didn't get the same. Can you test this please. Thanks.

**Comment by JunweiLiang** [comment]
A few google searches got me [this](https://stackoverflow.com/questions/22488872/cv2-imshow-and-cv2-imwrite). And I'm sure it is also related to the OpenCV version...

**Comment by farecomhalima** [comment]
Top :) Thanks
solution proposed: img = np.array(img,dtype=float)/float(255)
