### ISSUE TITLE
Check failed: c->in_use() && (c->bin_num == kInvalidBinNum)

### ISSUE THREAD

**Issue by NinaCai** [JunweiLiang/Object_Detection_Tracking#3]
I am using python3 + tf 1.12.
I changed the code to make it compatible with python 3.
print str -> print(str)
import cPickle as pickle -> import pickle
cat_id =label -> cat_id = int(label)   #looks like the label is not int but int64?
xrange->range

and it runs for a while and then it gives me this error: 
2019-07-03 17:09:18.558069: F tensorflow/core/common_runtime/bfc_allocator.cc:458] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum)
Aborted

Any idea why it is happening? Thanks.

**Comment by JunweiLiang** [comment]
Seems to be a TF bug for tf 1.12: https://github.com/tensorflow/tensorflow/issues/22750

Could you try either tf 1.10/tf 1.13/ tf 1.14? They are the ones that I have tested.

**Comment by NinaCai** [comment]
Got it, thanks!

**Comment by JunweiLiang** [comment]
Closing this for now.
