### ISSUE TITLE
dnn tensorflow

### ISSUE THREAD

**Issue by farecomhalima** [JunweiLiang/Object_Detection_Tracking#30]
Hi, I have a question about your code: can we use  cv2.dnn.readNetFromTensorflow(model, prtxt) to read the model with weights?
I can not find the file .pbtxt , if you have an idea how can i generate it with the file .config

**Comment by JunweiLiang** [comment]
Why do you need to load tensorflow with opencv? The .pbtxt file should exist in the variable model format, but most of our models are frozen graph. [Here](https://github.com/JunweiLiang/Object_Detection_Tracking#models) the object_v2 model should be in the variable model format and should have a .pbtxt file.

**Comment by farecomhalima** [comment]
I'm new in this domaine. I think that using cv2.dnn.readNetFromTensorflow can make the inference faster. Do you agree? if not what do you suggest to improve the speed of inference (out of TensorRT)

**Comment by JunweiLiang** [comment]
The main contribution of this repo is to have an efficient framework for object detection and tracking inference. Check out the latest updates [here](https://github.com/JunweiLiang/Object_Detection_Tracking#updates) and the full speed experiments [here](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/SPEED.md#122020-multiple-image-batch-processing). We can finish processing a 5-minute video in 1 minute 45 seconds with a ~1080 TI GPU.
To improve speed, we basically went from variable model -> frozen graph -> prune model -> multi-image batch -> multi-thread.

**Comment by farecomhalima** [comment]
Thank you for your answer. Last question: In this github there is a script for Fine Tuning, Transfer Learning?

**Comment by JunweiLiang** [comment]
Sure. Please read through the README. There are training and test instructions [here](https://github.com/JunweiLiang/Object_Detection_Tracking#training--testing). You can load the ActEV model and then finetuning on a new dataset.

**Comment by farecomhalima** [comment]
Hi I have just a question: what do you think about **model distillation** to have a model speed and precise for Faster RCNN ?

**Comment by JunweiLiang** [comment]
Yes! Suppose you could distill knowledge from a Resnet-101-backbone FPN to a Resnet-50 or even Resnet-34, you get 30% ~ 50% speed improvement.
