### ISSUE TITLE
Data for train 

### ISSUE THREAD

**Issue by kevinyena** [JunweiLiang/Object_Detection_Tracking#31]
Hi Junwei, i would like to train the pretained model by following your instructions. In the first step you said we could download the data from Actev website, i search [here](https://actev.nist.gov/) for a moment but i don't see the data set cooresponding to 'v1-training_012019_actgt_allsingle_npz' ? How could i download the frames please ?

**Comment by JunweiLiang** [comment]
The download links are from their website: https://gitlab.kitware.com/actev/actev-data-repo
And also you can download the videos from virat website here: https://data.kitware.com/#collection/56f56db28d777f753209ba9f/folder/56f57e748d777f753209bed6
