### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by farecomhalima** [JunweiLiang/Object_Detection_Tracking#32]
Hello I have download the model  obj_v2 and obj_v3 but i can't find the config file .pbtxt
Thanks

**Comment by JunweiLiang** [comment]
The models we provided are saved using tf.train.Saver. We have also provided frozen graph (.pb files) model for obj_v3. There is no "config file" needed to load the models. The .pbtxt file format is the text version of the .pb file. See the difference between .pb and .pbtxt [here](https://stackoverflow.com/questions/51948262/difference-between-pb-and-pbtxt-in-tensorflow).

**Comment by farecomhalima** [comment]
OK, thanks. I agree with you but to have the pbtxt we need both pb file and the config file ".config" used for the training

**Comment by JunweiLiang** [comment]
With the files saved using tf.train.Saver in the .tgz, you can re-format the model into anything you like.
Also, there is no ".config" file used in training. See [here](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/TRAINING.md#training) for training instructions.
