### ISSUE TITLE
error while trying to visualize the results (on Windows OS)

### ISSUE THREAD

**Issue by saikrithik** [JunweiLiang/Object_Detection_Tracking#33]
![image](https://user-images.githubusercontent.com/55931692/106093107-b31bf380-6155-11eb-93c5-5db0665ad481.png)

**Comment by JunweiLiang** [comment]
This has something to do with previous steps. tracks_to_json.py assumes a track output path under which there are "Person"/"Vehicle" folder. What is the content in "test_track_out/"?

**Comment by saikrithik** [comment]
this is what I got in test_track_out
![image](https://user-images.githubusercontent.com/55931692/106125670-6d295480-6182-11eb-97ab-61e8c2cf7fc4.png)

**Comment by JunweiLiang** [comment]
I think it is a Windows thing. I tested the code in Ubuntu. Let me know what value do [this guy](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/tracks_to_json.py#L33) and [this guy](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/tracks_to_json.py#L37) have.

**Comment by saikrithik** [comment]
![image](https://user-images.githubusercontent.com/55931692/106848394-e8d15700-66d6-11eb-9dd8-3240b9cce380.png)
Here it is..

**Comment by saikrithik** [comment]
changing this [this](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/tracks_to_json.py#L37) to 
cat_name = detfile.split("\\")[1] got my code working.. thank you.

**Comment by JunweiLiang** [comment]
I have updated the code (see changes [here](https://github.com/JunweiLiang/Object_Detection_Tracking/commit/28343de99b6abdca57ff40b0572391d85ed10d0f)). Please help test whether this works. 

Reference: https://stackoverflow.com/questions/3167154/how-to-split-a-dos-path-into-its-components-in-python
