### ISSUE TITLE
Errors training frame-level activity (--bupt-exp)

### ISSUE THREAD

**Issue by brunokinder** [JunweiLiang/Object_Detection_Tracking#36]
Hi @JunweiLiang , I'm trying to train the model  for frame-level and I always have 0/any loaded and I noticed line 828 in `main.py`

`config.but_exp and classname in but_act_mapping`

when I look into the file `class_ids`  for `targetAct2id_bupt` and `bupt_act_mapping`  I think this is always false and I never load the images.  I followed the instructions with the same parameters. Am I missing something?

Thanks

**Comment by brunokinder** [comment]
Nevermind. I found the problem. For some reason, the list of `anno['actlabels'] `is a list of bytes. Maybe different versions of python..

**Comment by JunweiLiang** [comment]
Probably. I remembered the labels are created using python 2.7. Thanks.
