### ISSUE TITLE
Extract box RoI feature

### ISSUE THREAD

**Issue by shanshuo** [JunweiLiang/Object_Detection_Tracking#4]
Hi Junwei,

Great work and thanks for sharing. I want to extract RoI feature given the box. In `main.py` I find `boxfeat()` but failed to execute it. It seems that `get_model_boxfeat()` is missing. How to do it?

**Comment by JunweiLiang** [comment]
Hi,

You can take a look at https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/obj_detect_tracking.py#L390

And modify models.py to take boxes as input, replacing the RPN boxes with your input boxes here https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/models.py#L465

I will release this part of the code in a month at the future prediction repo.

Thanks
