### ISSUE TITLE
Question about enqueuer_thread, which led the long time waiting. 

### ISSUE THREAD

**Issue by xqcn** [JunweiLiang/Object_Detection_Tracking#41]
Hello, thank you very much for the open source code.  It is very helpful!

When I use the queuer script for my own videos, sometimes the video can not be processed and it seems that the queue is wating for the data but can not get it. Have you got some sight for this situation?

By the way, the script seems use only one GPU when I have 2 GPU and set the --gpu 2. 

The Script:
`python obj_detect_tracking_multi_queuer_tmot.py --model_path data/obj_v5_model --version 5 --video_dir /data/  --video_lst_file k1615.lst --frame_gap 8 --im_batch_size 16  --get_tracking --tracking_dir k1615_tmot --log_time_and_gpu --gpu 2 --use_all_mem`

Shell output:
 ```
 0%|                       | 0/22 [00:00<?, ?it/s]
^CTraceback (most recent call last):███████████████▏| 206/207 [12:04<00:03,  3.23s/it]
  File "obj_detect_tracking_multi_queuer_tmot.py", line 740, in <module>
    for batch in tqdm(get_batches, total=video_queuer.num_batches):
  File "/usr/local/lib/python3.6/site-packages/tqdm/std.py", line 1097, in __iter__
    for obj in iterable:
  File "/xxx/xxx/cmu_track/enqueuer_thread.py", line 295, in get
    sample = self.queue.get(block=True)
  File "/usr/local/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
  0%|                       | 0/22 [1:15:29<?, ?it/s]
100%|██████████████████████████████████▏| 206/207 [1:15:29<00:21, 21.99s/it]
```

**Comment by xqcn** [comment]
It seems that when the item number is odd, such as "207", the error appears, but the even number does not lead to the mistake. Now I am using the .pb file for my videos and it runs well. Thank you for your code and prompt reply!

**Comment by JunweiLiang** [comment]
That sounds like a bug. If you have time, could you share a video and commands you used to reproduce the issue? Thanks.

**Comment by JunweiLiang** [comment]
@xqcn

**Comment by xqcn** [comment]
Sorry for the late response! I am busy on other things, but you can simply make videos that have odd or even frame numbers considering the batch size to reproduce this bug.
