### ISSUE TITLE
Can I use the repo to detect score board.

### ISSUE THREAD

**Issue by zydjohnHotmail** [JunweiLiang/Object_Detection_Tracking#42]
Hello:
I want to know, in one live basketball game video. There is one scoreboard in the TV screen, its position is fixed, but the score in the scoreboard is changing quite often.
I want to know if I can use the repo to detect the scoreboard, I need its scoreboard position in the screen, and further, can I detect the score change in the scoreboard.
For example, at the beginning, the score is: 0-0, if one team scores, then the score becomes 2-0.
Can I detect the position of scoreboard and detect the score changes in it?
If yes, please give a general instruction on how to do this.
Thanks,

**Comment by JunweiLiang** [comment]
You’ll need to prepare training data of scoreboard bounding boxes and train the model from scratch. This repo is mostly for person/vehicle inference.
