### ISSUE TITLE
Evaluation of Detector with DeepSort

### ISSUE THREAD

**Issue by Divyasha02** [JunweiLiang/Object_Detection_Tracking#43]
Hello Sir, 
I would like to know which technique had you used to evaluate DeepSort model. 

Here https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/COMMANDS.md#10-2020-comparing-efficientdet-with-maskrcnn-on-video-datasets you have compared EfficientDet with MaskRCNN on video datasets. Did you try doing MaskRCNN with Deepsort? 

I want to display mask of pedestrian while using Deepsort. I am able to do it successfully for displaying bounding boxes with Mask_RCNN + DeepSort, but not able to display mask. Any help is highly appreciated. Thank you

**Comment by JunweiLiang** [comment]
This code base already has DeepSORT and TMOT tracking: https://github.com/JunweiLiang/Object_Detection_Tracking#tracking-with-tmot-algo-and-reid
To get mask outputs, you only need to add `--add_mask`: https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/obj_detect_tracking_multi_queuer.py#L209
