### ISSUE TITLE
Is the code for real time? about the multi-camera tracking

### ISSUE THREAD

**Issue by alexHxun** [JunweiLiang/Object_Detection_Tracking#45]
Thank you for your awesome work!
 I want to affirm if the tmot is real time? I noticed you used a for loop when dealing with multiple cameras in multi-video-reid.py:
`for time_slot in tqdm(camera_data["sync_groups"]):` in line 448.
Does you put all the frames of one video in the queue first and process track in per frame , then you handle all videos one by one?

**Comment by JunweiLiang** [comment]
tmot algorithm itself is very lightweight and the object detection and tracking is very fast. The multi-threaded code in [here](https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/obj_detect_tracking_multi_queuer_tmot.py#L733) reads the frames using CPU meanwhile running object detection on GPU (then tracking on CPU).

But for the multi-camera case, I have not tested them extensively and currently the code should be incomplete.
