### ISSUE TITLE
How to download the model?

### ISSUE THREAD

**Issue by umbrellait-maksim-titarenko** [JunweiLiang/Object_Detection_Tracking#46]
It seems that the way described in README:

`$ wget https://aladdin-eax.inf.cs.cmu.edu/shares/diva_obj_detect_models/models/obj_v3_model.tgz `

doesn't work:

`wget: unable to resolve host address ‘aladdin-eax.inf.cs.cmu.edu’`

Can someone please share the test videos and the model?

**Comment by JunweiLiang** [comment]
I have fixed the links in README. The ones you mentioned could be accessed through `https://precognition.team`
