### ISSUE TITLE
where can i download BUPT-MCPRL slides

### ISSUE THREAD

**Issue by houzhijian** [JunweiLiang/Object_Detection_Tracking#5]
Hi, JunweiLiang:
      
      I see you update your comparison with BUPT-MCPRL.
      According to your given link, this is the official slide, I wonder where you download  BUPT slides...
      Thank you for your response.

**Comment by JunweiLiang** [comment]
I took pictures of their slides during their workshop session. You gonna have to ask them for the slides as I couldn’t find them as well.
