### ISSUE TITLE
need the ActEV instruction

### ISSUE THREAD

**Issue by iuhiyuh** [JunweiLiang/Object_Detection_Tracking#8]
Hello, great work, but I have a few questions:
1. 'Activity Box Experiments' in the Model section in README.md. Why did the experimental results on ActEV not use the setting of 'Object v6'? It looks like it has better performance.
2. could you add instruction for training and testing in ActEV?

**Comment by JunweiLiang** [comment]
I don't use the SE-net since it is slower (and obj_v5 -> obj_v6 is only a slight improvement). Will add instructions for activity box experiments next week.

**Comment by iuhiyuh** [comment]
Thanks!

**Comment by iuhiyuh** [comment]
@JunweiLiang Hello, I have read your code but have not seen the part of building frame-level tubes with dp algorithm. May I have missed it?

**Comment by JunweiLiang** [comment]
This repo only contains the code for object detection and tracking. The activity box experiment is evaluated on every frame. Will add instructions by the end of the week.

**Comment by iuhiyuh** [comment]
got it, thanks again.

**Comment by JunweiLiang** [comment]
https://github.com/JunweiLiang/Object_Detection_Tracking/blob/master/ACTIVITY_BOX.md

**Comment by iuhiyuh** [comment]
- hello, I wonder if you will add the part of box merge and GMM mentioned in your paper?
- I noticed that the 'mixup' in the code is missing from the anno file, which seems to be the merged box. Is that so, please
- https://github.com/JunweiLiang/Object_Detection_Tracking/blob/0d2058d9132f0f71be83a79f87a74076a70f5ae6/vis_json.py#L238
This line seems to be an alternative to GMM, and I noticed that it filters a lot of background
