### ISSUE TITLE
Issue running sample command.

### ISSUE THREAD

**Issue by melkiga** [JunweiLiang/Object_Detection_Tracking#9]
Hi! I'm trying to execute your updated code on a single video file. I modified the paths in your sample command to suit the ones on my machine and I get an Assertion error that looks like the following:
`Traceback (most recent call last):
  File "./obj_detect_tracking_cmu_new/obj_detect_tracking.py", line 429, in <module>
    vcap = VideoReader(videofile)
  File "/home/gmelki1/activity-detection/argus-images/obj_detect_tracking_cmu_new/diva_io/video/reader.py", line 53, in __init__
    self._init()
  File "/home/gmelki1/activity-detection/argus-images/obj_detect_tracking_cmu_new/diva_io/video/reader.py", line 219, in _init
    assert len(self._packets) == self._stream.duration
AssertionError`

Any ideas?
Thanks!

**Comment by JunweiLiang** [comment]
I need more information. This looks like your video is corrupted.

1. What's the output of ffprobe of your video?
2. Does opencv frame extraction work? (run without `--use_lijun`)
3. Does MoviePy frame extraction work? (run without `--use_lijun` and with `--use_moviepy`)

If you are sure that your video is not corrupted, put the video online somewhere so @lijun can test it.

**Comment by Lijun-Yu** [comment]
This is a known issue of `diva_io` v0.2 on some corrupted videos, which has been fixed in `diva_io` [v0.3](https://github.com/Lijun-Yu/diva_io/tree/v0.3). I would recommend @JunweiLiang to update correspondingly to fix this.

**Comment by JunweiLiang** [comment]
@melkiga Please add the three outputs I mentioned above.

**Comment by melkiga** [comment]
Thanks for the response. I was able to get it running by running the command with `--use_lijun`. I'm positive the video is not corrupted.

**Comment by JunweiLiang** [comment]
FYI, the code is updated with `diva_io` [v0.3](https://github.com/Lijun-Yu/diva_io/tree/v0.3) now.

**Comment by melkiga** [comment]
Thanks, appreciate the heads up.
